CREATE TABLE ritmo_event (
                             id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             bairro      VARCHAR(120) NOT NULL,
                             turno       VARCHAR(16)  NOT NULL, -- MANHA/TARDE/NOITE
                             energia     INT          NOT NULL, -- 0..2
                             ambiente    INT          NOT NULL, -- 0..2
                             condicao    INT          NOT NULL, -- 0..2
                             enviado_em  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ritmo_bairro_turno ON ritmo_event (bairro, turno);
