CREATE TABLE RITMO_EVENT (
                             ID           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             BAIRRO       VARCHAR2(120) NOT NULL,
                             TURNO        VARCHAR2(16)  NOT NULL, -- MANHA/TARDE/NOITE
                             ENERGIA      NUMBER(1)     NOT NULL, -- 0..2
                             AMBIENTE     NUMBER(1)     NOT NULL, -- 0..2
                             CONDICAO     NUMBER(1)     NOT NULL, -- 0..2
                             ENVIADO_EM   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IDX_RITMO_BAIRRO_TURNO ON RITMO_EVENT (BAIRRO, TURNO);
